### PR TITLE
Allow loading on macOS 15 without -lilubetaall

### PR DESCRIPTION
**Pull request by Lorys89**

### CODE REVIEW

**Review by Tweak4141 — APPROVED** [review]

**Review by AlfCraft07 — APPROVED** [review]

**Comment by pokewizardSAM** [comment]
I wonder how long is this pr gonna take now

**Comment by AlfCraft07** [comment]
> I wonder how long is this pr gonna take now

yeah

**Comment by AlfCraft07** [comment]
if I can't code and did it anyway in less than 10 minutes they can certainly do it

**Comment by AlfCraft07** [comment]
See ChefKissInc/NootedRed#275

**Pull request merged**
